class UserRole:
    RESIDENT = 'RESIDENT'
    RESIDENT_ADVISOR = 'RESIDENT_ADVISOR'
    STAFF = 'STAFF'
    OFFICE_MANAGER = 'OFFICE_MANAGER'
    BUILDING_MANAGER = 'BUILDING_MANAGER'
    ADMIN = 'ADMIN'
